name: fin_project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.10
  - scikit-learn>=1.3
  - matplotlib>=3.7
  - seaborn>=0.12
  - joblib>=1.3
  - pip
  - pip:
      - xgboost>=2.0.0
      - torch>=2.0.0
      - pandas-datareader>=0.10.0
